apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rabbitmq-system

# ğŸ‡ Rabbitmq cluster operator
resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.17.0/cluster-operator.yml

patches:
  - target:
      kind: Namespace
      name: rabbitmq-system
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: rabbitmq-system
      $patch: delete