apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ğŸ‡ RabbitMQ Messaging Topology Operator (with cert-manager)
  - https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.18.0/messaging-topology-operator-with-certmanager.yaml
