apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: direct-exchange
spec:
  name: direct-exchange
  vhost: demo-vhost
  type: direct
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq-demo
